
[[constraint]]
  branch = "master"
  name = "github.com/sirupsen/logrus"

[[constraint]]
  branch = "master"
  name = "github.com/k0kubun/pp"

[[constraint]]
  branch = "master"
  name = "github.com/kotakanbe/logrus-prefixed-formatter"

[[constraint]]
  branch = "master"
  name = "github.com/ymomoi/goval-parser"

[[constraint]]
  branch = "master"
  name = "github.com/cheggaaa/pb"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"
